// weekly-blog-digest
// Sends a Monday morning email summary of new draft blog posts from the past week.

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const RECIPIENT = "support@tidywisecleaning.com";
const FROM = "TidyWise Blog Bot <noreply@jointidywise.com>";
const SITE_URL = "https://jointidywise.com";

function scoreColor(score: number | null): string {
  if (score === null) return "#6b7280";
  if (score >= 80) return "#10b981";
  if (score >= 60) return "#f59e0b";
  return "#ef4444";
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

  const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

  try {
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
    const { data: drafts, error } = await supabase
      .from("blog_posts")
      .select("id, title, target_keyword, word_count, quality_score, created_at")
      .eq("status", "draft")
      .gte("created_at", sevenDaysAgo)
      .order("created_at", { ascending: false });

    if (error) throw error;
    const draftCount = drafts?.length || 0;

    if (draftCount === 0) {
      return new Response(
        JSON.stringify({ ok: true, skipped: true, reason: "No new drafts this week" }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!RESEND_API_KEY) {
      return new Response(
        JSON.stringify({ ok: false, error: "RESEND_API_KEY not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const rows = drafts!
      .map(
        (d) => `
        <tr>
          <td style="padding:12px;border-bottom:1px solid #e5e7eb;">
            <a href="${SITE_URL}/admin/blog/${d.id}/edit" style="color:#0f172a;font-weight:600;text-decoration:none;">
              ${d.title}
            </a>
            <div style="color:#64748b;font-size:13px;margin-top:4px;">
              ${d.target_keyword || "—"} · ${(d.word_count || 0).toLocaleString()} words
            </div>
          </td>
          <td style="padding:12px;border-bottom:1px solid #e5e7eb;text-align:right;">
            <span style="display:inline-block;padding:4px 10px;border-radius:6px;font-weight:600;color:white;background:${scoreColor(
              d.quality_score
            )};font-size:13px;">
              ${d.quality_score ?? "—"}/100
            </span>
          </td>
        </tr>`
      )
      .join("");

    const html = `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#0f172a;">
        <h1 style="font-size:24px;margin:0 0 8px;">📝 ${draftCount} new blog draft${draftCount === 1 ? "" : "s"} ready</h1>
        <p style="color:#64748b;margin:0 0 24px;">Generated by the TidyWise blog automation in the past 7 days. Review and approve before publishing.</p>

        <table style="width:100%;border-collapse:collapse;background:white;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
          ${rows}
        </table>

        <div style="margin-top:24px;text-align:center;">
          <a href="${SITE_URL}/admin/blog?status=draft"
             style="display:inline-block;padding:12px 24px;background:#0f172a;color:white;text-decoration:none;border-radius:6px;font-weight:600;">
            Review All Drafts
          </a>
        </div>

        <p style="color:#94a3b8;font-size:12px;margin-top:32px;text-align:center;">
          TidyWise Blog System · Automated weekly digest
        </p>
      </div>
    `;

    const emailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: FROM,
        to: [RECIPIENT],
        subject: `📝 ${draftCount} new blog draft${draftCount === 1 ? "" : "s"} ready for review`,
        html,
      }),
    });

    if (!emailRes.ok) {
      const text = await emailRes.text();
      throw new Error(`Resend error ${emailRes.status}: ${text.substring(0, 300)}`);
    }

    return new Response(
      JSON.stringify({ ok: true, sent: true, draftCount }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("weekly-blog-digest error:", e);
    return new Response(
      JSON.stringify({ ok: false, error: e instanceof Error ? e.message : String(e) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
