// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-organizations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.88.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function resolveOrganizationId(supabase, requested) {
  const { data, error } = await supabase.from("org_memberships").select("organization_id, role").order("created_at", { ascending: true }).order("id", { ascending: true });
  if (error) return { error: error.message };
  const rows = data ?? [];
  if (rows.length === 0) return { error: "You are not a member of any organization." };
  if (requested) {
    const match = rows.find((r) => r.organization_id === requested);
    if (!match) return { error: "You are not a member of that organization." };
    return { organizationId: match.organization_id };
  }
  const owner = rows.find((r) => r.role === "owner");
  return { organizationId: (owner ?? rows[0]).organization_id };
}

// src/lib/mcp/tools/list-organizations.ts
var list_organizations_default = defineTool({
  name: "list_organizations",
  title: "List my businesses",
  description: "List the TidyWise organizations (businesses) the signed-in user belongs to, with their role in each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("org_memberships").select("organization_id, role, organizations(name, slug, plan_tier)").order("created_at", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const organizations = (data ?? []).map((row) => ({
      organization_id: row.organization_id,
      role: row.role,
      name: row.organizations?.name ?? null,
      slug: row.organizations?.slug ?? null,
      plan_tier: row.organizations?.plan_tier ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(organizations, null, 2) }],
      structuredContent: { organizations }
    };
  }
});

// src/lib/mcp/tools/list-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_bookings_default = defineTool2({
  name: "list_bookings",
  title: "List bookings",
  description: "List cleaning bookings for one of the signed-in user's organizations, optionally filtered by date range and status.",
  inputSchema: {
    organization_id: z.string().optional().describe("Organization to read. Defaults to the user's owner organization."),
    from: z.string().optional().describe("Only bookings scheduled on or after this ISO date/time."),
    to: z.string().optional().describe("Only bookings scheduled on or before this ISO date/time."),
    status: z.string().optional().describe("Filter by booking status, e.g. confirmed or completed."),
    limit: z.number().optional().describe("Maximum rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ organization_id, from, to, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const resolved = await resolveOrganizationId(supabase, organization_id);
    if ("error" in resolved) {
      return { content: [{ type: "text", text: resolved.error }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("bookings").select(
      "id, booking_number, scheduled_at, status, service_type, address, city, total_price, payment_status, frequency, is_arrival_window, arrival_window_start, arrival_window_end, customer_id"
    ).eq("organization_id", resolved.organizationId).order("scheduled_at", { ascending: true }).order("id", { ascending: true }).limit(take);
    if (from) query = query.gte("scheduled_at", from);
    if (to) query = query.lte("scheduled_at", to);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { organization_id: resolved.organizationId, bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_customers_default = defineTool3({
  name: "list_customers",
  title: "List customers",
  description: "Search or list customers for one of the signed-in user's organizations by name, email, or phone.",
  inputSchema: {
    organization_id: z2.string().optional().describe("Organization to read. Defaults to the user's owner organization."),
    search: z2.string().optional().describe("Match against first name, last name, or email."),
    limit: z2.number().optional().describe("Maximum rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ organization_id, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const resolved = await resolveOrganizationId(supabase, organization_id);
    if ("error" in resolved) {
      return { content: [{ type: "text", text: resolved.error }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("customers").select(
      "id, first_name, last_name, email, phone, city, state, customer_status, is_recurring, created_at"
    ).eq("organization_id", resolved.organizationId).is("merged_into", null).order("created_at", { ascending: false }).order("id", { ascending: true }).limit(take);
    if (search) {
      const term = search.replace(/[%,]/g, " ").trim();
      query = query.or(
        `first_name.ilike.%${term}%,last_name.ilike.%${term}%,email.ilike.%${term}%`
      );
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { organization_id: resolved.organizationId, customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_invoices_default = defineTool4({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices for one of the signed-in user's organizations, optionally filtered by status such as draft, sent, paid, or overdue.",
  inputSchema: {
    organization_id: z3.string().optional().describe("Organization to read. Defaults to the user's owner organization."),
    status: z3.string().optional().describe("Filter by invoice status."),
    limit: z3.number().optional().describe("Maximum rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ organization_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const resolved = await resolveOrganizationId(supabase, organization_id);
    if ("error" in resolved) {
      return { content: [{ type: "text", text: resolved.error }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("invoices").select(
      "id, invoice_number, status, total_amount, subtotal, due_date, sent_at, paid_at, customer_id, created_at"
    ).eq("organization_id", resolved.organizationId).order("created_at", { ascending: false }).order("id", { ascending: true }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { organization_id: resolved.organizationId, invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-customer.ts
import { defineTool as defineTool5, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_customer_default = defineTool5({
  name: "create_customer",
  title: "Create customer",
  description: "Create a new customer record in one of the signed-in user's organizations. Use list_customers first to avoid duplicates.",
  inputSchema: {
    first_name: z4.string().trim().min(1).describe("Customer first name."),
    last_name: z4.string().trim().min(1).describe("Customer last name."),
    email: z4.string().trim().min(1).describe("Customer email address."),
    phone: z4.string().trim().optional().describe("Customer phone number."),
    address: z4.string().trim().optional().describe("Street address."),
    city: z4.string().trim().optional(),
    state: z4.string().trim().optional(),
    zip_code: z4.string().trim().optional(),
    notes: z4.string().trim().optional().describe("Internal notes about this customer."),
    organization_id: z4.string().optional().describe("Organization to write to. Defaults to the user's owner organization.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const resolved = await resolveOrganizationId(supabase, input.organization_id);
    if ("error" in resolved) throw new ToolError(resolved.error);
    const { organization_id: _ignored, ...fields } = input;
    const { data, error } = await supabase.from("customers").insert({ ...fields, organization_id: resolved.organizationId }).select("id, first_name, last_name, email, phone, city, state, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { customer: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "slwfkaqczvwvvvavkgpr";
var mcp_default = defineMcp({
  name: "jointidywise",
  title: "Jointidywise",
  version: "0.1.0",
  instructions: "Tools for TidyWise, a multi-tenant cleaning business CRM. Callers act as their signed-in TidyWise user and can only reach organizations they are a member of. Use `list_organizations` first to find an organization id, then `list_bookings`, `list_customers`, or `list_invoices`. Use `create_customer` to add a new customer.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_organizations_default,
    list_bookings_default,
    list_customers_default,
    list_invoices_default,
    create_customer_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
